# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170402_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
